#config_version=6

mode:
  start_events: ball_started
  stop_events:  
  priority: 100


######################## EXTRA BALL SCORE #################
extra_balls:
  score_one:
    enabled: true
    award_events: player_score{value>=1500000}
  score_two:
    enabled: false
    award_events: player_score{value>=210000}
  score_three:
    enabled: false
    award_events: player_score{value>=300000}   

######################## ATIVADORES DE MODOS #################

counters:
  ### ATIVA MULTIBALL
  spinner_rotations:
    count_events: left_corridor_spinner_shot_hit
    count_complete_value: 10
    events_when_complete: Ativa_Modo_Multiball
    reset_on_complete: true 
    disable_on_complete: false

 ### AVANCA BONUS 
  my_counter:
    starting_count: 0
    count_complete_value: 6
    count_events: rollover_lanes_lit_complete
    reset_on_complete: true
    disable_on_complete: false

light_player:
  "{device.counters.my_counter.value > 0}":
    l_bonusx100: 
      color: blue
      fade: 100ms
  "{device.counters.my_counter.value > 1}":
    l_bonusx1000: 
      color: blue
      fade: 100ms
      
  "{device.counters.my_counter.value > 2}":
    1_bonusx2000:
       color: blue
       fade: 100ms
  "{device.counters.my_counter.value > 3}":
    l_bonusx5000: 
      color: orange
      fade: 200ms
  "{device.counters.my_counter.value > 4}":
    l_bonusx7000: 
      color: red
      fade: 200ms

event_player:
    Ativa_Modo_Multiball: start_mode_multiball  
       

######################## SLIDES ##############################  
slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 21
        y: 40%
      - type: text
        text: PLAYER (number)
        x: 5%
        y: 65%
        anchor_x: left
        anchor_y: bottom
        font_size: 8
        
      - type: text
        text: BALL (ball)
        y: 65%
        x: right-55
        anchor_x: right
        anchor_y: bottom
        font_size: 8
      - type: text
        text: "(machine|credits_string)"
        y: 65%
        x: right-5
        anchor_x: right
        anchor_y: bottom
        font_size: 8
        

show_player:
  rollover_lanes_lit_complete: 
    rollover_lanes_complete:
      speed: 20
      loops: 10
      priority: 1
   
  
  TIME_droptargets_lit_complete:
    TIME_complete:
      speed: 20
      loops: 10
      priority: 1

  TRAVEL_droptargets_lit_complete:
    TRAVEL_complete:
      speed: 20
      loops: 0
      priority: 1
  
  mode_base_started:
    start_base_showlight:
      speed: 5
      loops: -1
      priority: 2
  TIME_droptargets_complete:     # assim se para um showplayer
   start_base_showlight:
    action: stop
      
######################## SOUNDS ##############################
sound_player:
  mode_base_started:
    lets_go:
      action: play
      loops: 0
  rollover_lanes_complete:
    go:
      action: play
      loops: 0

  TIME_droptargets_lit_complete:
    time:
      action: play
      loops: 0

  TRAVEL_droptargets_lit_complete:
    time:
      action: play
      loops: 0 
  
  TIME_droptargets_counter_complete: #criar condicional para tocar apenas na 3z vez do counter, eliminando o audio anterior (ate 2a vez)
    go:
      action: play
      loops: 0

######################## SHOTS ##############################
shots:
# Spinners
  left_corridor_spinner_shot:
    switch: s_left_corridor_spinner
    show_tokens:
      light: l_left_corridor
  left_corridor_spinner2_shot:
    switch: s_left_corridor_spinner2
    show_tokens:
      light: l_left_corridor_2
  right_corridor_spinner_shot:
    switch: s_right_corridor_spinner
    show_tokens:
      light: l_right_corridor

# Top Left Standup 2
  top_left_standup2_shot:
    switch: s_top_left_standup2
    show_tokens: 
      light: l_top_left_standup_2
# Top Left Standup 
  top_left_standup_shot:
    switch: s_top_left_standup
    show_tokens: 
      light: l_top_lef_standup
# Left Standup 
  left_standup_shot:
    switch: s_left_standup
    show_tokens: 
      light: l_left_standup
# Right Standup 
  right_standup_shot:
    switch: s_right_standup
    show_tokens: 
      light: l_right_standup


# Rollover
  left_rollover_shot:
    switch: s_left_rollover
    show_tokens:
      light: l_left_rollover
  center_rollover_shot:
    switch: s_center_rollover
    show_tokens:
      light: l_center_rollover
  right_rollover_shot:
    switch: s_right_rollover
    show_tokens:
      light: l_right_rollover

# right scoop
  right_scoop_shot:
    switch: s_right_scoop
    show_tokens:
     light: l_right_scoop
# center scoop
  center_scoop_shot:
    switch: s_center_scoop
    show_tokens:
      light: l_left_center_target_avance1
# left scoop
  left_scoop_shot:
    switch: s_left_scoop
    show_tokens:
     light: l_left_scoop

# TIME Droptarget
  T:
    switch: s_T
    show_tokens: 
      light: l_T
  I:
    switch: s_I
    show_tokens: 
      light: l_I
  M:
    switch: s_M
    show_tokens: 
      light: l_M
  E:
    switch: s_E
    show_tokens: 
      light: l_E

# CENTER Droptargets
  left_center_droptarget:
    switch: s_left_center_target
    show_tokens: 
      light: l_left_center_target 
  center_center_droptarget:
    switch: s_center_center_target
    show_tokens: 
      light: l_center_center_target
  right_center_droptarget:
    switch: s_right_center_target
    show_tokens: 
      light: l_right_center_target

# TRAVEL Droptarget
  Tb:
    switch: s_standup_1
    show_tokens: 
      light: l_standup_1
  R:
    switch: s_standup_2
    show_tokens: 
      light: l_standup_2
  A:
    switch: s_standup_3
    show_tokens: 
      light: l_standup_3
  V:
    switch: s_standup_4
    show_tokens: 
      light: l_standup_4
  Eb:
    switch: s_standup_5
    show_tokens: 
      light: l_standup_5
  L:
    switch: s_standup_6
    show_tokens: 
      light: l_standup_6
  
# Bumpers
  bumper1_shot:
    switch: s_bumper1
  bumper2_shot:
    switch: s_bumper2
     
# Botton lanes  
  right_inlane_shot:
    switch: s_right_inlane
    show_tokens:
      light: l_right_inlane
  left_inlane_shot:
    switch: s_left_inlane
    show_tokens:
      light: l_left_inlane
  right_outlane_shot:
    switch: s_right_outlane
    show_tokens:
      light: l_right_out_lane
  left_outlane_shot:
    switch: s_left_outlane
    show_tokens:
      light: l_left_out_lane

  # Lane light change by flipper
shot_groups:
  rollover_lanes:
    shots: left_rollover_shot, center_rollover_shot, right_rollover_shot
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active
    reset_events: rollover_lanes_lit_complete  
  
  # TIME Droptargets
  TIME_droptargets:
    shots: T, I, M, E
    reset_events: TIME_droptargets_lit_complete
  # CENTER Droptargets
  CENTER_droptargets:
    shots: left_center_droptarget, center_center_droptarget, right_center_droptarget
    reset_events: CENTER_droptargets_lit_complete
  # TRAVEL Droptargets
  TRAVEL_droptargets:
    shots: Tb, R, A, V, Eb, L
    reset_events: TRAVEL_droptargets_lit_complete
    
  
######################## SCORE ##############################

variable_player:

  left_corridor_spinner_shot_hit:
    score: 50
  left_corridor_spinner2_shot_hit:
    score: 50
  right_corridor_spinner_shot_hit:
    score: 50

  top_left_standup2_shot_hit:
    score: 100
  top_left_standup_shot_hit:
    score: 100
  left_standup_shot_hit:
    score: 100
  right_standup_shot_hit:
    score: 100
  
  right_scoop_shot_hit:
    score: 350
  center_scoop_shot_hit:
    score: 500
  left_scoop_shot_hit:
    score: 350

  right_inlane_shot_hit:  
    score: 100
  left_inlane_shot_hit:  
    score: 100
  right_outlane_shot_hit:  
    score: 500
  left_outlane_shot_hit:  
    score: 500
 
  left_rollover_shot_hit:
    score: 100
  center_rollover_shot_hit:
    score: 200
  right_rollover_shot_hit:
    score: 300
  rollover_lanes_lit_complete: 
    score: 5000

  bumper1_shot_hit:
    score: 100
  bumper2_shot_hit:
    score: 100

  TIME_droptargets_hit:
    score: 500

  TIME_droptargets_lit_complete:
    score: 400000
  
  TRAVEL_droptargets_hit:
    score: 500
  
  TRAVEL_droptargets_lit_complete:
    score: 400000
  
  left_center_droptarget_hit:
    score: 350
  center_center_droptarget_hit:
    score: 350
  right_center_droptarget_hit:
    score: 350
   
  

