#config_version=6

switches:
  #Botom Switches

  s_left_flipper:
    number: 10
    tags: left_flipper
  s_right_flipper:
    number: 11
    tags: right_flipper
  
  s_trough1:
    number: 2 
    type: NC
  s_trough2:
    number: 3 
    type: NC
  s_trough3:
    number: 4 
    type: NC
  s_trough4:
    number: 5 
    type: NC
  s_trough5:
    number: 6 
    type: NC
  s_trough6:
    number: 7 
    type: NC
  s_trough_jam:
    number: 8 
    type: NC

  s_plunger:
    number: 9
  s_start:
    number: 15
    tags: start

  #Botom Lanes Switches  
  s_right_inlane:
    number: 16
    tags: right_inlane, playfield_active
  s_left_inlane:
    number: 17
    tags: left_inlane, playfield_active
  s_left_outlane:
    number: 18
    tags: left_outlane
  s_right_outlane:
    number: 19
    tags: right_outlane
  
  #Upper Rollover Switches
  s_left_rollover:
    number: 100
    tags: left_rollover
  s_center_rollover:
    number: 101
    tags: center_rollover
  s_right_rollover:
    number: 102
    tags: right_rollover
  
# Droptarget TIME
  s_T:
    number: 150
    tags: T_droptarget
  s_I:
    number: 151
    tags: I_droptarget
  s_M:
    number: 152
    tags: M_droptarget
  s_E:
    number: 153
    tags: E_droptarget
  
  s_standup_1:
    number: 154
    tags: standup_1 
  s_standup_2:
    number: 155
    tags: standup_2
  s_standup_3:
    number: 156
    tags: standup_3
  s_standup_4:
    number: 157
    tags: standup_4
  s_standup_5:
    number: 158
    tags: standup_5
  s_standup_6:
    number: 159
    tags: standup_6

  s_left_center_target:
    number: 160
    tags: left_center_target
  s_center_center_target:
    number: 161
    tags: center_center_target
  s_right_center_target:
    number: 162
    tags: right_center_target
 
 # Corridor Spinners
  s_left_corridor_spinner:
    number: 163
    tags: left_corridor_spinner
  s_left_corridor_spinner2:
    number: 164
    tags: left_corridor_spinner2
  s_right_corridor_spinner:
    number: 165
    tags: right_corridor_spinner
  s_launcher_lane_spinner:
    number: 166
    tags: launcher_lane_spinner
 
 # Stand Ups 
  s_left_standup:
    number: 167
    tags: left_standup
  s_top_left_standup:
    number: 168
    tags: top_left_standup
  s_top_left_standup2:
    number: 169
    tags: top_left_standup2
  s_right_standup:
    number: 170
    tags: right_standup

 # Scoops
  s_left_scoop:
    number: 171
    tags: left_scoop
  s_center_scoop:
    number: 172
    tags: center_scoop
  s_right_scoop:
    number: 173
    tags: right_scoop

# Bumpers
  s_bumper1:
    number: 174
    tags: bumper1, jets
  s_bumper2:
    number: 175
    tags: bumper2, jets

  
#autofire
  s_sling_left:
    number: 200
  s_sling_right:
    number: 201

drop_targets:
  T:
    switch: s_T
    reset_coil: c_reset_droptarget_TIME
  I:
    switch: s_I
    reset_coil: c_reset_droptarget_TIME
  M:
    switch: s_M
    reset_coil: c_reset_droptarget_TIME
  E:
    switch: s_E
    reset_coil: c_reset_droptarget_TIME

drop_target_banks:
  TIME:
    drop_targets: T, I, M, E
    reset_coils: c_reset_droptarget_TIME
    reset_on_complete: 1s
       
  
   