#config_version=6

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger   

# configs separados 
config:
 - config_sounds.yaml
 - config_ball_devices.yaml
 - config_coils.yaml
 - config_flippers.yaml
 - config_switches.yaml
 - config_lights.yaml
 - config_credits.yaml
 - config_droptargets.yaml
 
modes:
 - base
 - skillshot
 - super_jets_setup
 - super_jets
 - special_setup
 - special
 - credits
  

displays:
  window:
    width: 600
    height: 200
  dmd:
    width: 128
    height: 32
    default: true
window:
  width: 600
  height: 200 
  title: Mission Pinball Framework
slides:
  window_slide_1:
    - type: display
      effects:
        - type: dmd
          dot_color: ff5500
      width: 512
      height: 128
    - type: text
      text: MISSION PINBALL FRAMEWORK
      color: ff550055
      anchor_y: top
      y: top-3
      font_size: 30
    - type: rectangle
      width: 514
      height: 130
      color: ff550055

slide_player:
  init_done:
    window_slide_1:
      target: window

player_vars:
  sj_active:
    value_type: int
    initial_value: 0


  

keyboard:
  z:
    switch: s_left_flipper
  x:
    switch: s_right_flipper
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  p:
    switch: s_plunger
  s:
    switch: s_start
  q:
    switch: s_right_inlane
  c:
    switch: s_coin_left
  w:
    switch: s_service_coin

 

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
  - s_trough5
  - s_trough6

