#config_version=6

mode:
  start_events: Special_Go, Ativa_Modo
  stop_events: right_standup_shot_hit
  priority: 500

variable_player:
  right_standup_shot_hit:
    score: 1000000


     
counters:
  special_counter:
    count_events: right_standup_shot_hit
    count_complete_value: 1
    events_when_complete: special


show_player:
  mode_special_started:
    special_slide:
      loops: 0
    special_showlight:
      speed: 40

# SOUNDS
sound_player:
  mode_special_started:
    special_sound:
      action: play
      loops: -1